---

version: '3.7'
services:
  sig-backend:
      build: sig-backend
      container_name: sig-backend
      deploy:
        replicas: 1
      ports:
        - "3000:3000"

  sig-frontend:
    build: sig-frontend
    container_name: sig-frontend
    deploy:
      replicas: 1
    ports:
      - "80:80"
    depends_on:
      - "sig-backend"
