---

version: '3.7'
services:
  sig-backend:
      build: sig-backend
      container_name: sig-backend
      ports:
        - "5000:5000"

  sig-frontend:
    build: sig-frontend
    container_name: sig-frontend
    volumes:
      - ./sig-frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    depends_on:
      - "sig-backend"
